// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfzcbcflxmjfdrbdnsvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmemNiY2ZseG1qZmRyYmRuc3ZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MTExNzgsImV4cCI6MjA1ODM4NzE3OH0._nuDQr0g-Tpfv19hq_TauFuH8zRbH6TxQx7IWdiPiOU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);